version: '3.8'

services:
  frontend:
    image: frontend-app
    ports:
      - "3000:3000"
    env_file:
      - ./PDSS/PDSS/PDSS-WEB-FRONT/environnement/.dev.env
    depends_on:
      - backend

  backend:
    image: backend-app:v2.0
    ports:
      - "5000:5000"
    env_file:
      - ./PDSS/PDSS/PDSS-WEB-BACK/.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes: 
      - C:/stagemobelite/PDSS/PDSS/db:/docker-entrypoint-initdb.d
    env_file:
      - C:/stagemobelite/PDSS/PDSS/db/.env 
