version: '3.8'
services:
  
  backend:
    image: ${DOCKER_USERNAME}/mob-app-backend-${TAG}
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - src/environment/.dev.env

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env