  backend:
    image: ${DOCKER_USERNAME}/mob-app-backend-${TAG}
    ports:
      - "5000:5000"
    env_file:
      - back.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env 
