# Utilisation d'une image Node.js légère comme base
FROM node:14 

# Définition du répertoire de travail dans le conteneur
WORKDIR /usr/src/app

# Copier les fichiers de package.json et package-lock.json (si présent)
COPY package*.json ./

# Installation des dépendances
RUN npm install 

# Copier le reste des fichiers de l'application
COPY . .

# Exposer le port sur lequel l'application s'exécute
EXPOSE 5000

RUN npm run build:dev 

# Commande d'exécution de l'application / commande eli fi CMD hua lcommande eli executiha ki naamel docker run
CMD ["npm" , "run", "node ./bin/www "]