name: Deploy with Docker Compose
#..
on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Fetch latest tags for frontend and backend
        run: |
          FRONTEND_TAG=$(curl -s "https://registry.hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/frontend/tags" | jq -r '."results"[]["name"]' | head -n 1)
          BACKEND_TAG=$(curl -s "https://registry.hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/backend/tags" | jq -r '."results"[]["name"]' | head -n 1)
          echo "FRONTEND_TAG=${FRONTEND_TAG}" >> $GITHUB_ENV
          echo "BACKEND_TAG=${BACKEND_TAG}" >> $GITHUB_ENV

      - name: Change tags in Docker Compose file
        run: |
          sed -i 's|image: frontend-app.*|image: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ env.FRONTEND_TAG }}|' docker-compose.yml
          sed -i 's|image: backend-app.*|image: ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.BACKEND_TAG }}|' docker-compose.yml

      - name: Copy Docker Compose file to VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VM_HOST: 10.0.2.15
          VM_USER: sonia
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $VM_HOST >> ~/.ssh/known_hosts
          scp docker-compose.yml $VM_USER@$VM_HOST:/home/sonia/depploymentCD

      - name: Deploy with Docker Compose on VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VM_HOST: 10.0.2.15
          VM_USER: sonia
        run: |
          ssh $VM_USER@$VM_HOST << 'EOF'
            cd /home/sonia/depploymentCD
            docker-compose down
            docker-compose up -d
            docker image prune -f
          EOF

      - name: Logout from DockerHub
        run: docker logout
