name: CI for Frontend

on:
  push:
    branches:
      - main
    paths:
      - '/PDSS-WEB-FRONT/**'
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Debug - List files in PDSS-WEB-FRONT
        run: ls -al PDSS-WEB-FRONT

      - name: Debug - Display Node.js version
        run: node -v

      - name: Debug - Display npm version
        run: npm -v

      - name: Debug - List files in environnement
        run: ls -al PDSS-WEB-FRONT/environnement

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: PDSS-WEB-FRONT
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
          file: PDSS-WEB-FRONT/Dockerfile

      - name: Remove unused Docker images
        run: docker image prune -f

      - name: Logout from DockerHub 
        run: docker logout