name: CI for Frontend

on:
  push:
    branches:
      - main
    paths:
      - '/PDSS-WEB-FRONT/**'
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2 #github marketplace contain the action related to the commande in black box 
        with:
          context: PDSS-WEB-FRONT
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}

      - name: Remove unused Docker images
        run: docker image prune -f

      - name: Logout from DockerHub 
        run: docker logout