name: CI/CD pdss-front 

on:
  push:
    branches:
      - main
    paths:
      - '/PDSS-WEB-FRONT/**'
      - '.github/**'

jobs:
  builds:
    runs-on: pdss-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

          # set the image tag to the GitHub commit ID....
      - name: Set Variables
        id: vars
        run: echo "image_tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Change tags in Docker Compose file
        run: |
          sed -i 's|image: pdss-front.*|image: ${{ secrets.DOCKER_USERNAME }}/mob-app:${{ steps.vars.outputs.image_tag }}|' PDSS-WEB-FRONT/docker-compose.yml
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}



      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: PDSS-WEB-FRONT
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mob-app-${{ steps.vars.outputs.image_tag }}
          file: PDSS-WEB-FRONT/Dockerfile  
  Deployment:
    runs-on: pdss-runner
    
    steps:
      - name: Deploy to VM
        run: |
            docker-compose up -d
        working-directory: PDSS-WEB-FRONT/docker-compose.yml
